-- 2단계: 공개 정적 파일 밖으로 가상 메모를 옮기기 위한 학습용 테이블
-- 실제 개인정보나 실제 키를 넣지 않습니다.

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

-- 클라이언트 역할에는 테이블 권한을 주지 않습니다.
revoke all on table public.notes from anon, authenticated;
revoke all on sequence public.notes_id_seq from anon, authenticated;

-- 1단계의 공개 가상 메모를 학습용 DB로 옮깁니다.
insert into public.notes (owner_id, title, content)
values
  (null, '과제', '실습용 가상 과제 기록'),
  (null, '포트폴리오', '실습용 가상 포트폴리오 기록'),
  (null, '아침 리추얼', '실습용 가상 리추얼 기록'),
  (null, '훈련 행정 자료', '실습용 가상 행정 기록');
